### ISSUE TITLE
not working with cjs require

### ISSUE THREAD

**Issue by olsonpm** [ndaidong/bellajs#132]
It looks like this project is built to support cjs require, however in a fresh project the following error is returned

> Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/node_modules/bellajs/dist/bella.js from /path/to/file.js not supported.

I got it working locally by renaming `dist/bella.js` to `dist/bella.cjs` then updating the exports.require property in package.json.

Is cjs require something you're interested in supporting ?  I will create a PR if so

---

reproduction steps

```sh
$ mkdir test-cjs && cd test-cjs
$ npm init -f && npm i bellajs
$ node -e 'require("bellajs")'
```

**Comment by ndaidong** [comment]
Yes, it only works with standard ESM syntax now.
